---

- name: "Get info about ec2 instance"
  ec2_instance_facts:
   filters:
      "tag:Name": "jenkins"
      "instance-state-name": ["running" ]
  register: ec2_metadata


- debug:
    msg: "{{ ec2_metadata }}"
  when: "debug_aws | default(False) "


- set_fact:
    ec2_user: "ubuntu"
    ec2_public_dns_name: "{{ ec2_metadata.instances[0].public_dns_name }}"
    ec2_id: "{{ ec2_metadata.instances[0].instance_id }}"


- debug:
    msg: "AWS ec2 instace public dns: {{ ec2_public_dns_name }}"
  when: "debug_aws | default(False) "
