---

- name: "Get info about ec2 instance"
  ec2_instance_facts:
   filters:
      "tag:Name": "jenkins"
      "instance-state-name": ["running" ]
  register: ec2_metadata


- debug:
    msg: "{{ ec2_metadata }}"
  when: "debug_aws | default(False) "


- name: "Remove ec2 instance"
  local_action:
    module: ec2
    state: 'absent'
    instance_ids: "{{ ec2_metadata.instances[0].instance_id }}"
    wait: True
  when: "ec2_metadata.instances | length > 0"
