- hosts: localhost
  connection: local
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"

  vars:
    debug_aws: True
    ec2_key_name: "private-cloud-work"
    create_ec2: True
    create_ebs: True
  vars_files:
    - vars/jenkins/config.yml

  roles:
    - role: install
      tags: install
    - role: vpc
      tags: vpc
    - role: ec2-keys
      tags: ec2-keys
    - role: ec2
      tags: ec2


  tasks:
    - name: "Add host: {{ ec2_public_dns_name }} to inventory"
      add_host:
        name: "ec2-instance"
        ansible_ssh_host: "{{ ec2_public_dns_name }}"
        ansible_user: "{{ ec2_user }}"
        groups: "ec2"
        ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/private-jenkins-ec2"
        ansible_python_interpreter: "/usr/bin/python3"


    - debug:
        msg: "{{ groups }}"


- hosts: ec2-instance
  gather_facts: yes
  vars_files:
    - vars/jenkins/config.yml


  pre_tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'
      become: yes


  roles:
    - role: ebs-format
      tags: ebs-format
    - role: java
      tags: java
    - role: jenkins
      tags: jenkins
  become: yes
